feat/automated-upgrades-rollback (#7)
* test: adding ingress lb to dns via tf

* test: fix

* fix

* fix

* test

* test

* test fix

* test

* test

* final test fix

* added route53 tf file

* fixes

* fixes

* final test

* feat: update route53 records

* test fix

* testing alternate

* fix issue route53.tf

* feat: rollback when failure

* updated deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -4,7 +4,7 @@ on:
   push:
     branches:
       - 'deploy/**'
-      - 'feat/k8s'
+      - 'feat/k8s-updates'
       - main
 
 env:
@@ -118,6 +118,7 @@ jobs:
         uses: actions/checkout@v4.2.2
 
       - name: "Deploy Helm Chart for OpenTelemetry-Demo App (Remote SSH)"
+        id: deploy_oteldemo_helm
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ env.k8s_mgmt_ip }}
@@ -127,7 +128,38 @@ jobs:
             cd /home/ec2-user/helm
             /home/ec2-user/helm/deploy_helm.sh
             echo "Deployed Helm Chart Successfully"
+            
+            echo "Exporting the Ingress ALB Name"
+            INGRESS_ALB_NAME=$(kubectl get ingress -n helm-otel-demo -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}' | cut -d '-' -f 1-4)
+            
+            if [ -z "$INGRESS_ALB_NAME" ]; then
+              echo "Error: Ingress ALB hostname is empty. Exiting."
+              exit 1
+            fi
+            echo "$INGRESS_ALB_NAME"
 
+      - name: "Set up AWS CLI"
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
+
+      - name: "Set up Terraform"
+        uses: hashicorp/setup-terraform@v2.0.3
+        with:
+          terraform_version: 1.11.2
+          terraform_wrapper: false
+
+      - name: "Set the Ingress ALB Record into Route53"
+        run: |
+          cp post_app_deploy/*.tf .
+          echo "Setting the Ingress ALB Record into Route53"
+          export TF_VAR_otel_app_alb_name="otel-demo-frontend-alb"
+          terraform init
+          terraform plan -out=otel.plan -var="ssh_private_key=${{ secrets.K8S_EC2_SSH_PRIVATE_KEY }}"
+          terraform apply -var="ssh_private_key=${{ secrets.K8S_EC2_SSH_PRIVATE_KEY }}" -auto-approve otel.plan
+        continue-on-error: false
 
   deploy_k8s_manifests:
     runs-on: ubuntu-latest
@@ -159,6 +191,11 @@ jobs:
       - name: "Checkout"
         uses: actions/checkout@v4.2.2
 
+      - name: "Wait for Application to be Ready"
+        run: |
+          echo "Waiting for the application load balancers to be deployed completely..."
+          sleep 120
+
       - name: "Run Tests on Deployed Otel-demo Application (Remote SSH)"
         uses: appleboy/ssh-action@v1.0.3
         with:
@@ -167,4 +204,18 @@ jobs:
           key: ${{ secrets.K8S_EC2_SSH_PRIVATE_KEY }}
           script: |
             cd /home/ec2-user/tests
-            /home/ec2-user/k8s/test_deployment.sh
+            /home/ec2-user/tests/test_deployment.sh
+            STATUS=$?
+            if [ $STATUS -ne 0 ]; then
+              REVISION_COUNT=$(helm history helm-otel-demo -n helm-otel-demo --output json | jq length)
+              echo "Revision count: $REVISION_COUNT"
+              if [ "$REVISION_COUNT" -gt 1 ]; then
+                echo "Rolling back $RELEASE_NAME..."
+                helm rollback helm-otel-demo -n helm-otel-demo
+              else
+                echo "Cannot rollback: only one or no revision exists. Check the deployment."
+              fi
+              exit 1
+            else
+              echo "Tests passed successfully."
+            fi
